services:
  postgres:
    image: postgres:13
    container_name: boxify_db
    restart: always
    environment:
      POSTGRES_DB: boxify
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
